language: go
go: 
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - tip

matrix:
  allow_failures:
    - go: tip

install:
 - rm -rf $GOPATH/src/github.com/haoyixin
 - mkdir -p $GOPATH/src/github.com/haoyixin
 - ln -s $PWD $GOPATH/src/github.com/haoyixin/go-syslog.v2
 - cd $GOPATH/src/github.com/haoyixin/go-syslog.v2 && go get -v -t ./...
 
script:
 - cd $GOPATH/src/github.com/haoyixin/go-syslog.v2 && go test -v ./...
 
sudo: false
